// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 11/22/2025, 7:09:49 PM
import "@nuxtjs/tailwindcss/config-ctx"
import configMerger from "@nuxtjs/tailwindcss/merger";

import cfg2 from "./../../tailwind.config.js";
import cfg3 from "./../../tailwind.config.js";
const config = [
{"content":{"files":["/Users/wilsonm/development/m3dp-uip/frontend/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/wilsonm/development/m3dp-uip/frontend/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/wilsonm/development/m3dp-uip/frontend/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/wilsonm/development/m3dp-uip/frontend/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/wilsonm/development/m3dp-uip/frontend/plugins/**/*.{js,ts,mjs}","/Users/wilsonm/development/m3dp-uip/frontend/composables/**/*.{js,ts,mjs}","/Users/wilsonm/development/m3dp-uip/frontend/utils/**/*.{js,ts,mjs}","/Users/wilsonm/development/m3dp-uip/frontend/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/wilsonm/development/m3dp-uip/frontend/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","/Users/wilsonm/development/m3dp-uip/frontend/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","/Users/wilsonm/development/m3dp-uip/frontend/app.config.{js,ts,mjs}"]}},
{},
cfg2,
cfg3
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = config;

export default resolvedConfig;
